# Generated by Django 3.1.7 on 2021-03-19 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('date', models.DateField(default=datetime.date(2021, 3, 19))),
                ('place', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
