# Generated by Django 3.1.7 on 2021-03-19 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210319_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 18, 42, 38, 929645, tzinfo=utc)),
        ),
    ]
