# Generated by Django 3.1.7 on 2021-03-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210321_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='event',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
